"""users.id add public_id

Revision ID: 8ddd9d2a3331
Revises: d2f4eba57de2
Create Date: 2025-07-05 07:21:25.861295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ddd9d2a3331'
down_revision: Union[str, None] = 'd2f4eba57de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=True))
    op.execute("UPDATE users SET public_id = gen_random_uuid() WHERE public_id IS NULL")
    op.alter_column("users", "public_id", nullable=False)

    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_column('users', 'public_id')
    # ### end Alembic commands ###
